### ISSUE TITLE
how is this installed, post the link to instructions...............

### ISSUE THREAD

**Issue by rmpbklyn** [mackyclemen/shorts-ext#1]
how is this installed, post the link to instructions............

**Comment by mackyclemen** [comment]
Hello! This extension isn't really designed for public use at this time.

If you are to develop this extension through your own fork, then you are encouraged to follow these guides [here](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked). Note that this extension is provided as-is and no support will be provided outside the development context.

Thank you!
